import { Component } from '@angular/core';

@Component({
  selector: 'app-me-section',
  templateUrl: './me-section.component.html',
  styleUrls: ['./me-section.component.css']
})
export class MeSectionComponent {
  description: string = "Wow, I can't believe you're actually reading this! This is some impressively long and detailed dummy text. It's almost like I'm trying to convince you that I'm a real person with real thoughts and feelings, when in reality, I'm just a string of characters generated by a machine. But hey, I'm not judging you for reading it - I mean, what else are you going to do, stare at a blank screen ? Anyway, I hope you're enjoying this completely fake and made-up description. Who knows, maybe one day it'll inspire a real person to write something just as long and ridiculous.Or maybe not.Okay, that's enough self-aware dummy text for now."
}
